/**Problem 2: Each new term in the Fibonacci sequence is 
generated by adding the previous two terms. 

By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
Solved By: Shengyuan Guo in 2013
**/

#include <stdio.h>

int main()
{
    
    printf("Sum of even valued terms of Fibonacci Seq <4 million: %d", natural35(1000));
}

int evenfib()
{
    int sum=0;
    // Use an arr to memoize the process 
    // improve efficency
    int fibArr[4000000]={0};
    for(int n=0;; n++)
    {
        int temp=fib(n);
        if(temp>4000000)
        {
         break;
        }
        if(temp%2==0)
        {
            sum+=temp;
        }
    }
    return sum;

}

int fib(int n, int fibArr[])
{
    if{fibArr[]}
    if(n==0)
        return 0;
    else if(n==1)
        return 1;
    else
        return fib(n-1)+fib(n-2);

}
int fibHelper(int n, int arr[])
